export const S = {
  appTitle: "Transmogrifier",
  dropZoneHint: "Drop files here or click to add",
  dropZoneSub: "Supports MOV, MP4, MKV, AVI, WMV, WebM, MP3, WAV, FLAC and more",
  addFiles: "Add Files",
  clearAll: "Clear All",
  convert: "Convert",
  cancel: "Cancel",
  outputFormat: "Output format",
  quality: "Quality",
  saveTo: "Save to",
  sameFolderAsSource: "Same folder as source",
  chooseFolder: "Choose…",
  converting: (position: number, total: number, pct: number) =>
    `Converting ${position} of ${total} · ${pct}%`,
  conversionDone: "Done",
  conversionFailed: "Failed",
  showInFinder: "Show in Finder",
  copyLog: "Copy log",
  suffix: " (converted)",
  audioExtractNote: "Audio will be extracted from video",
  parallel: "Parallel",
  copied: "Copied!",
  showLog: "Show log",
  trim: "Trim",
  trimStart: "Start",
  trimEnd: "End",
  trimClear: "Clear trim",
  trimInvalid: "End must be after start and within the clip",
  advanced: "Advanced",
  videoCodec: "Codec",
  resolution: "Resolution",
  framerate: "FPS",
  crfOverride: "CRF",
  hwAccel: "Hardware encoding",
  audioBitrate: "Audio kbps",
  stripMetadata: "Strip metadata",
  keep: "Keep",
  ffmpegFlags: "FFmpeg flags",
  fastTrimHint: "Fast trim: no re-encode (cuts snap to keyframes)",
  conflictTitle: "Files already exist",
  conflictBody: (n: number) =>
    n === 1
      ? "This file already exists in the output location:"
      : `These ${n} files already exist in the output location:`,
  conflictOverwrite: "Overwrite",
  conflictKeepBoth: "Keep both",
  conflictCancel: "Don't convert",
  exitTitle: "Conversions in progress",
  exitBody: (n: number) =>
    n === 1
      ? "A conversion is still in progress. Quit and cancel it? The partial output file will be removed."
      : `${n} conversions are still in progress. Quit and cancel them? Partial output files will be removed.`,
  exitQuit: "Quit anyway",
  exitStay: "Keep converting",
  poweredByFfmpeg: "Powered by FFmpeg",
  reading: "Reading…",
  loadingFiles: "Reading files…",
  updateAvailable: (version: string) => `Update ${version} available`,
  updateInstall: "Restart & update",
  updateInstalling: "Updating…",
};
